consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  Status:
    description: Status  of API and connections to remote services (default view)
    example:
      database: false
      queue: true
    properties:
      database:
        description: Is database connected and working?
        example: false
        type: boolean
      queue:
        description: Is queue connected and working?
        example: true
        type: boolean
    required:
    - database
    - queue
    title: 'Mediatype identifier: application/vnd.status+json; view=default'
    type: object
host: localhost:8080
info:
  description: Testing code and doc generation with goa
  title: Practice for goa
  version: ""
paths:
  /status:
    get:
      description: Get status of server and connections
      operationId: status#show
      produces:
      - application/vnd.status+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Status'
      schemes:
      - http
      summary: show status
      tags:
      - status
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  OK:
    description: OK
    schema:
      $ref: '#/definitions/Status'
schemes:
- http
swagger: "2.0"
