consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  Asset:
    description: An asset can be pretty much anything (default view)
    example:
      _id: Perspiciatis vel soluta fugit tenetur.
      createdAt: 2002-12-31T18:55:28Z
      data: false
      name: sm4hz
      type: car
      updatedAt: 2003-07-18T22:44:26Z
    properties:
      _id:
        description: Object ID attribute
        example: Perspiciatis vel soluta fugit tenetur.
        type: string
      createdAt:
        description: timestamp of when the asset was created
        example: 2002-12-31T18:55:28Z
        format: date-time
        type: string
      data:
        description: Type specific data
        example: false
      name:
        description: Name of asset
        example: sm4hz
        minLength: 3
        type: string
      type:
        description: Type of asset
        enum:
        - car
        example: car
        type: string
      updatedAt:
        description: timestamp of when the asset was updated
        example: 2003-07-18T22:44:26Z
        format: date-time
        type: string
    title: 'Mediatype identifier: application/vnd.asset+json; view=default'
    type: object
  AssetCollection:
    description: AssetCollection is the media type for an array of Asset (default
      view)
    example:
    - _id: Perspiciatis vel soluta fugit tenetur.
      createdAt: 2002-12-31T18:55:28Z
      data: false
      name: sm4hz
      type: car
      updatedAt: 2003-07-18T22:44:26Z
    items:
      $ref: '#/definitions/Asset'
    title: 'Mediatype identifier: application/vnd.asset+json; type=collection; view=default'
    type: array
  CreateAssetPayload:
    example:
      data: 0.89316684
      name: 6ov5w
      type: car
    properties:
      data:
        description: Type specific data
        example: 0.89316684
      name:
        description: Name of asset
        example: 6ov5w
        minLength: 3
        type: string
      type:
        description: Type of asset
        enum:
        - car
        example: car
        type: string
    required:
    - name
    - type
    - data
    title: CreateAssetPayload
    type: object
  Status:
    description: Status  of API and connections to remote services (default view)
    example:
      database: false
    properties:
      database:
        description: Is database connected and working?
        example: false
        type: boolean
    required:
    - database
    title: 'Mediatype identifier: application/vnd.status+json; view=default'
    type: object
  UpdateAssetPayload:
    example:
      data: 0.4868256
      name: 1n6
      type: car
    properties:
      data:
        description: Type specific data
        example: 0.4868256
      name:
        description: Name of asset
        example: 1n6
        minLength: 3
        type: string
      type:
        description: Type of asset
        enum:
        - car
        example: car
        type: string
    title: UpdateAssetPayload
    type: object
host: localhost:8080
info:
  description: Testing code and doc generation with goa
  title: Practice for goa
  version: ""
paths:
  /asset:
    get:
      description: Get all assets
      operationId: asset#showAll
      produces:
      - application/vnd.asset+json; type=collection
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/AssetCollection'
      schemes:
      - http
      summary: showAll asset
      tags:
      - asset
    post:
      description: Create new assets
      operationId: asset#create
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/CreateAssetPayload'
      produces:
      - application/vnd.asset+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Asset'
      schemes:
      - http
      summary: create asset
      tags:
      - asset
  /asset/{assetID}:
    delete:
      description: Delete specific asset
      operationId: asset#delete
      parameters:
      - description: _id of an asset
        in: path
        name: assetID
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      schemes:
      - http
      summary: delete asset
      tags:
      - asset
    get:
      description: Get specific asset
      operationId: asset#show
      parameters:
      - description: _id of an asset
        in: path
        name: assetID
        required: true
        type: string
      produces:
      - application/vnd.asset+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Asset'
      schemes:
      - http
      summary: show asset
      tags:
      - asset
    put:
      description: Update specific asset
      operationId: asset#update
      parameters:
      - description: _id of an asset
        in: path
        name: assetID
        required: true
        type: string
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UpdateAssetPayload'
      produces:
      - text/plain
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
      schemes:
      - http
      summary: update asset
      tags:
      - asset
  /docs:
    get:
      description: ReDoc documentation generated from the swagger.json file
      operationId: documentation#show
      produces:
      - text/html; charset=utf-8
      responses:
        "200":
          description: OK
      schemes:
      - http
      summary: show documentation
      tags:
      - documentation
  /status:
    get:
      description: Get status of server and connections
      operationId: status#show
      produces:
      - application/vnd.status+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Status'
      schemes:
      - http
      summary: show status
      tags:
      - status
  /swagger.json:
    get:
      operationId: swagger#/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
      summary: Download generated/public/swagger/swagger.json
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  NotFound:
    description: Not Found
  OK:
    description: OK
schemes:
- http
swagger: "2.0"
